CREATE TABLE TODOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    COMPLETED BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IDX_TODOS_COMPLETED ON TODOS (COMPLETED);
CREATE INDEX IDX_TODOS_CREATED_AT ON TODOS (CREATED_AT);

CREATE TABLE TODO_LABELS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    COLOR VARCHAR(32),
    DELETED INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IDX_TODO_LABELS_NAME ON TODO_LABELS (NAME);
CREATE INDEX IDX_TODO_LABELS_DELETED ON TODO_LABELS (DELETED);
