CREATE TABLE TODOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    COMPLETED BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IDX_TODOS_COMPLETED ON TODOS (COMPLETED);
CREATE INDEX IDX_TODOS_CREATED_AT ON TODOS (CREATED_AT);
