CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR2(16) NOT NULL,
  total NUMBER(10) NOT NULL
);

INSERT INTO orders (status, total) VALUES ('NEW', 10);
INSERT INTO orders (status, total) VALUES ('PAID', 20);
INSERT INTO orders (status, total) VALUES ('NEW', 30);
COMMIT;
